### ISSUE TITLE
Are multiple baseDirs or symlinks supported?

### ISSUE THREAD

**Issue by kulmanf** [ckfinder/ckfinder-docs-samples-java#1]
I have the use case, where I want to show two unrelated directories to the user. And it should be possible, to move files from one directory to the other.

**Is it possible to have multiple base directories?**
Same question as: https://stackoverflow.com/questions/56563081/is-it-possible-to-combine-multiple-basedirs-in-one-ckfinder-view

One work-around would be to have symbolic links, as they exist for the PHP Connector
https://ckeditor.com/docs/ckfinder/ckfinder3-php/configuration.html#configuration_options_backends  
**Will the CKFinder Java version 3.5 support symlinks?**
(I've just tried to activate it in the demo, but the _followSymlinks_ flag doesn't seem to exist.)

Another work-around would be to have two CKFinder instances, but then it is not possible to move files from one folder to another (**please correct me, if I'm wrong** 😃)

**Comment by zaak** [comment]
Hi @kulmanf! I'm sorry for a late reply.

> Is it possible to have multiple base directories?

Yes, it is just a matter of the configuration. You can use `backends` and `resourceTypes` configuration options to achieve this.

Let's assume you want to give the user access to two separate base directories in the physical filesystem:

1. `/foo/bar/files`, which will be shown in CKFinder's view as "My Files" resource.
2. `/baz/images`, which will be shown in CKFinder's view as "My Images" resource.

The basic configuration for this case can be as follows:

```yaml
# (...)

backends:
  - name: 'my_files'
    adapter: 'local'
    root: '/foo/bar/files'
  - name: 'my_images'
    adapter: 'local'
    root: '/baz/images'

resourceTypes:
  - name: 'My Images'
    backend: 'my_images'
  - name: 'My Files'
    backend: 'my_files'
```

In CKFinder's view you will then see two resource types mapped to two separate base directories. You will be able to move and copy files between them.

![Screenshot_2019-11-10_09-31-05](https://user-images.githubusercontent.com/803299/68541256-7079ca00-039d-11ea-839e-22ff2fff74b4.png)

> Will the CKFinder Java version 3.5 support symlinks?

This depends on the operating system. On Linux directory symlinks will work out of the box.
